PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
     ?degree ?property ?object
} WHERE {
     PERSON_URI core:relatedBy ?advisingRelationship .
     ?advisingRelationship a core:AdvisingRelationship .
     ?advisingRelationship core:relates ?advisee .
     ?advisee a foaf:Person .
     ?advisee obo:RO_0000053 ?adviseeRole .
     ?adviseeRole a core:AdviseeRole .
     ?adviseeRole core:relatedBy ?advisingRelationship .
     ?advisee core:relates ?educationalTraining .
     ?educationalTraining a core:EducationalProcess .
     ?educationalTraining obo:RO_0002234 ?awardedDegree .
     ?awardedDegree core:relates ?degree .
     ?degree a core:AcademicDegree .
     ?degree ?property ?object
}