PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?person ?property ?object .
} WHERE {
     PERSON_URI core:advisorIn ?advisingRelationship .
     ?advisingRelationship core:advisee ?person .
     ?person ?property ?object .
}