PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?degree ?property ?object .
} WHERE {
     PERSON_URI core:advisorIn ?advisingRelationship .
     ?advisingRelationship core:degreeCandidacy ?degree .
     ?degree ?property ?object .
}