PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?educationalTraining ?property ?object .
} WHERE {
     PERSON_URI core:relatedBy ?advisingRelationship .
     ?advisingRelationship a core:AdvisingRelationship .
     ?advisingRelationship core:advisingContributionTo ?educationalTraining .
     ?educationalTraining ?property ?object .
}