PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#Thing> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?person1 vivo:relatedBy _:relationship .
    ?person2 vivo:relatedBy _:relationship .
    _:relationship vivo:relates ?person1 .
    _:relationship vivo:relates ?person2 .
} WHERE {
     {  ?person1 vivo:hasCollaborator ?person2 
        FILTER NOT EXISTS {
            ?person1 vivo:relatedBy ?relationship .
            ?relationship vivo:relates ?person2
        }
     }
}
