PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#Thing> 

CONSTRUCT {
    ?s vivo:orcidId ?orcidURI .
    ?orcidURI a owl:Thing .
} WHERE {
    ?s vivo:orcidId ?orcidString 
    FILTER(isLiteral(?orcidString))
    BIND(IRI(concat("http://orcid.org/", str(?orcidString))) AS ?orcidURI)
}
