PREFIX arg: <http://purl.obolibrary.org/obo/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX v:   <http://www.w3.org/2006/vcard/ns#> 
PREFIX vivo: <http://vivoweb.org/ontology/core#> 

CONSTRUCT {
    ?vcard v:hasTelephone _:telephone .
    _:telephone a v:Telephone .
    _:telephone a v:Voice .
    _:telephone v:telephone ?phoneNumber .
} WHERE {
    ?s vivo:phoneNumber ?phoneNumber .
    ?s arg:ARG_2000028 ?vcard .
    FILTER NOT EXISTS {
        ?vcard v:hasTelephone ?telephoneNode .
    }
}
