PREFIX arg: <http://purl.obolibrary.org/obo/> .
PREFIX foaf: <http://xmlns.com/foaf/0.1/> .
PREFIX v:   <http://www.w3.org/2006/vcard/ns#> .
PREFIX vivo: <http://vivoweb.org/ontology/core#> .

CONSTRUCT {
    ?s arg:ARG_2000028 _:vcard .
    _:vcard arg:ARG_2000029 ?s .
    _:vcard a v:Individual .
    _:vcard v:hasName _:name .
    _:name a v:Name .
    _:name v:givenName ?firstName .
    _:name vivo:middleName ?middleName .
    _:name v:familyName ?lastName .
    _:name v:hasEmail _:email .
    _:email a v:Email .
    _:email v:email ?email .
    _:name v:hasEmail _:primaryEmail .
    _:primaryEmail a v:Email .
    _:primaryEmail a v:Work .
    _:primaryEmail v:email ?primaryEmail . 
    _:name v:hasTelephone _:telephone .
    _:telephone a v:Telephone .
    _:telephone a v:Voice .
    _:telephone v:telephone ?phoneNumber .
    _:name v:hasTelephone _:primaryTelephone .
    _:primaryTelephone a v:Telephone .
    _:primaryTelephone a v:Voice .
    _:primaryTelephone a v:Work .
    _:primaryTelephone v:telephone ?primaryPhoneNumber .
    _:name v:hasTelephone _:fax .
    _:fax a v:Telephone .
    _:fax a v:Fax.
    _:fax v:telephone ?faxNumber . 
    _:name v:hasAddress _:address .
    _:address v:streetAddress ?
} WHERE {
    ?s a foaf:Person 
    {
        ?s foaf:firstName ?firstName .
    } UNION {
        ?s foaf:lastName ?lastName .
    } UNION {
        ?s vivo:middleName ?middleName 
    } UNION {
        ?s vivo:email ?email
    } UNION {
        ?s vivo:primaryEmail ?primaryEmail 
    } UNION {
        ?s vivo:phoneNumber ?phoneNumber 
    } UNION {
        ?s vivo:primaryPhoneNumber ?primaryPhoneNumber
    } UNION {
        ?s vivo:faxNumber ?faxNumber
    } UNION {
        ?s vivo:mailingAddress ?address .
        ?address vivo:addressCity ?addressCity .
        ?address vivo:addressState ?addressState .
        ?address vivo:addressCountry ?addressCountry .
        ?address vivo:addressPostalCode ?addressPostalCode .
        ?address vivo:address1 ?address1 .
        BIND (?address1 AS ?streetAddress) 
    } UNION {
        ?s vivo:mailingAddress ?address .
        ?address vivo:addressCity ?addressCity .
        ?address vivo:addressState ?addressState .
        ?address vivo:addressCountry ?addressCountry .
        ?address vivo:addressPostalCode ?addressPostalCode .
        ?address vivo:address1 ?address1 .
        ?address vivo:address2 ?address2 .
        BIND (CONCAT(?address1, ", ", ?address2)  AS ?streetAddress) 
    } UNION {   
        ?s vivo:mailingAddress ?address .
        ?address vivo:addressCity ?addressCity .
        ?address vivo:addressState ?addressState .
        ?address vivo:addressCountry ?addressCountry .
        ?address vivo:addressPostalCode ?addressPostalCode .
        ?address vivo:address1 ?address1 .
        ?address vivo:address2 ?address2 .
        ?address vivo:address3 ?address3 .
        BIND (CONCAT(?address1, ", ", ?address2, ", ", ?address3)  AS ?streetAddress) 
    } 
}
