PREFIX arg: <http://purl.obolibrary.org/obo/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX v:   <http://www.w3.org/2006/vcard/ns#> 
PREFIX vivo: <http://vivoweb.org/ontology/core#> 

CONSTRUCT {
    ?vcard v:hasEmail _:primaryEmail .
    _:primaryEmail a v:Email .
    _:primaryEmail a v:Work .
    _:primaryEmail v:email ?primaryEmail . 
} WHERE {
     ?s vivo:primaryEmail ?primaryEmail .
     ?s arg:ARG_2000028 ?vcard .
     FILTER NOT EXISTS {
         ?vcard v:hasEmail ?email .
         ?email a v:Work .
     }
}
