PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?agent vivo:relatedBy ?grant .
    ?grant vivo:relates ?agent
} WHERE {
    ?agent <http://purl.obolibrary.org/obo/RO_0000053> ?role .
    ?role vivo:relatedBy ?grant .
    { ?grant a vivo:Grant } UNION { ?grant a vivo:Contract }
    FILTER NOT EXISTS { ?grant vivo:relates ?agent } 
}
