PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX obo: <http://purl.obolibrary.org/obo/>

CONSTRUCT {
     ?publicationStatus ?property ?object .
} WHERE {
     PERSON_URI core:relatedBy ?authorship . 
     ?authorship a core:Authorship .
     ?authorship core:relates ?publication .
     ?publication a obo:IAO_0000030 .
     ?publication bibo:status ?publicationStatus .
     ?publicationStatus ?property ?object .
}