PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

CONSTRUCT {
     ?date ?property ?object .
     ?precision ?property2 ?object2 .
} WHERE {
     PERSON_URI core:relatedBy ?authorship . 
     ?authorship a core:Authorship .
     ?authorship core:relates ?publication .
     ?publication a obo:IAO_0000030 .
     ?publication ?dateTimeValue ?date .
     ?date ?property ?object .
     ?date core:dateTimePrecision ?precision .
     ?precision ?property2 ?object2 .
}