PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
     ?urllink ?property ?object .
} WHERE {
     PERSON_URI core:relatedBy ?authorship . 
     ?authorship a core:Authorship .
     ?authorship core:relates ?publication .
     ?publication a obo:IAO_0000030 .
     ?publication obo:ARG_2000028 ?vcard .
     ?vcard vcard:hasURL ?urllink .
     ?urllink ?property ?object .
}