PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
     ?geographicLocation ?property ?object .
} WHERE {
     PERSON_URI obo:ARG_2000028 ?vcard .
     ?vcard vcard:hasAddress ?address .
     ?address obo:RO_0001025 ?geographicLocation .
     ?geographicLocation ?property ?object .
}