PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?course ?property ?object .
} WHERE {
     PERSON_URI core:hasTeacherRole ?teacherRole .
     ?teacherRole core:roleRealizedIn ?course .
     ?course ?property ?object .
}