PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?organization ?property ?object .
} WHERE {
     PERSON_URI core:relatedBy ?issuedCredential . 
     ?issuedCredential a core:IssuedCredential . 
     ?issuedCredential core:relates ?credential .
     ?credential a core:Credential .
     ?credential core:hasGoverningAuthority ?organization .
     ?organization ?property ?object .
}