PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?issuedCredential ?property ?object .
} WHERE {
     PERSON_URI core:relatedBy ?issuedCredential . 
     ?issuedCredential a core:IssuedCredential . 
     ?issuedCredential ?property ?object .
}