PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?advisee vivo:adviseeIn ?advisingRelationship .
    ?advisingRelationship vivo:advisee ?advisee .
} WHERE {
    ?advisee vivo:adviseeIn ?advisingRelationship .
    OPTIONAL {
        ?advisingRelationship vivo:advisee ?advisee .
    }
}
