services:
  joai:
    hostname: joai
    container_name: joai
    volumes:
      - /joai/config:Z
      - /joai/data:Z
    environment:
      - VIVO_URL=http://vivo:${VIVO_CONTAINER_PORT}
    networks:
      - vivoweb
    ports:
      - ${JOAI_HOST_PORT}:${JOAI_CONTAINER_PORT}
      - ${JOAI_HOST_HTTPS_PORT}:${JOAI_CONTAINER_HTTPS_PORT}
    build:
      context: ./oai

