#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

Look through the uploads directory in the currently selected version, and insure
that an image file exists wherever the data model expects one.

This requires an imageFileInfo.csv, which was produced by a SPARQL query against
the data model.

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))
require "subscripts/upload_file_faker"

properties  = {}

properties["uploads_directory"] = version_file('data/uploads')
properties["file_info_file"] = "#{@home}/modelData/#{@site_name}/imageFileInfo.csv"
properties["template_file"] = "#{@home}/scripts/subscripts/dummy_image_file.jpg"

if ARGV.length == 1 && ARGV[0] == "doit"
  properties["scan_only"] = "false"
else
  puts "Just scanning unless you say: \"doit\""
  properties["scan_only"] = "true"
end

uff = UploadFileFaker.new(properties)
uff.process

puts "UploadFileFaker was successful."

