#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

Show the SVN status of the currently-selected distro, both VIVO and Vitro.

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))

if (@is_git)
  Dir.chdir(distro_file('Vitro')) { |path| system "svn status -u" }
  Dir.chdir(distro_file('VIVO'))  { |path| system "svn status -u" }
else
  Dir.chdir(distro_file('vitro')) { |path| system "svn status -u" }
  Dir.chdir(distro_file('vivo'))  { |path| system "svn status -u" }
end

