#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

What is the currently-selected version?

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require "#{File.dirname(__FILE__)}/subscripts/loadParms"

puts "Current version is #{@version_name}"

