#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

What is the currently-selected test?

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require "#{File.dirname(__FILE__)}/subscripts/loadParms"

puts "Current test is #{@test_name}, #{@test_threads} threads, #{@test_iterations} iterations"

