PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
     ?organization rdfs:label ?label 
} WHERE {
     PERSON_URI core:hasCredential ?issuedCredential . 
     ?issuedCredential core:issuanceOfCredential ?credential .
     ?credential core:hasGoverningAuthority ?organization .
     ?organization rdfs:label ?label .
}