PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?organization ?property ?object .
} WHERE {
     PERSON_URI core:hasCredential ?issuedCredential . 
     ?issuedCredential core:issuanceOfCredential ?credential .
     ?credential core:hasGoverningAuthority ?organization .
     ?organization ?property ?object .
}