PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?issuedCredential ?property ?object .
} WHERE {
     PERSON_URI core:hasCredential ?issuedCredential . 
     ?issuedCredential ?property ?object .
}