PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?date ?property ?object .
     ?precision ?property2 ?object2 .
} WHERE {
     PERSON_URI core:relatedBy ?issuedCredential . 
     ?issuedCredential a core:IssuedCredential . 
     ?issuedCredential core:expirationDate ?date .
     ?date ?property ?object .
     ?date core:dateTimePrecision ?precision .
     ?precision ?property2 ?object2 .
}