#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

View the VIVO log in Tomcat.

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))

puts system("less #{@home}/tomcat/logs/vivo.all.log")
