#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

Start following the tails of all of the logs in Tomcat.

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))

puts system("tail -f #{@home}/tomcat/logs/*")
