#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

Use SVN to get the latest revisions to the currently-selected distro.

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))

if (@is_git)
  Dir.chdir(distro_file('Vitro')) { |path| system "git pull" }
  Dir.chdir(distro_file('VIVO'))  { |path| system "git pull" }
else
  Dir.chdir(distro_file('vitro')) { |path| system "svn update" }
  Dir.chdir(distro_file('vivo'))  { |path| system "svn update" }
end
