#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

What is the currently-selected test?

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))

puts "Current test is #{@test_name}, #{@test_threads} threads, #{@test_iterations} iterations"

