#! /usr/bin/ruby

=begin
--------------------------------------------------------------------------------

What is the currently-selected version?

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
=end

require File.expand_path('subscripts/common', File.dirname(__FILE__))

puts "Current version is #{@version_name}"

