PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?award ?property ?object .
} WHERE {
     PERSON_URI core:awardOrHonor ?awardReceipt .
     ?awardReceipt core:receiptOf ?award . 
     ?award ?property ?object .
}