PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?containingEvent rdfs:label ?containingEventName
} WHERE {
     PERSON_URI core:hasPresenterRole ?presenterRole .
     ?presenterRole core:roleIn ?presentation .
     ?presentation core:eventWithin ?containingEvent .
     ?containingEvent rdfs:label ?containingEventName
}