PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
     ?position core:positionInOrganization ?organization .
     ?organization rdfs:label ?label .
} WHERE {
     PERSON_URI core:relatedBy ?position . 
     ?position a core:Position .
     ?position core:relates ?organization .
     ?organization a foaf:Organization . 
     ?organization rdfs:label ?label .
}