PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
    ?concept a skos:Concept .
} WHERE {
    { ?s vivo:hasResearchArea ?concept } UNION
    { ?s vivo:hasSubjectArea ?concept }
    FILTER NOT EXISTS {
        ?concept a skos:Concept
    }
}
