PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?organization ?property ?object .
} WHERE {
     PERSON_URI core:educationalTraining ?educationalTraining . 
     ?educationalTraining core:trainingAtOrganization ?organization .
     ?organization ?property ?object .
}