PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
     ?coAuthorship ?property1 ?object1 .
     ?person ?property2 ?object2 .   
} WHERE {
     PERSON_URI core:relatedBy ?authorship . 
     ?authorship a core:Authorship .
     ?authorship core:relates ?publication .
     ?publication a obo:IAO_0000030 .
     ?publication core:relatedBy ?coAuthorship .
     ?coAuthorship a core:Authorship .
     ?coAuthorship ?property1 ?object1 .
     ?coAuthorship core:relates ?person .
     ?person a foaf:Person .
     ?person ?property2 ?object2 .
}