PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?coAuthorship ?property1 ?object1 .
     ?person ?property2 ?object2 .   
} WHERE {
     PERSON_URI core:authorInAuthorship ?authorship . 
     ?authorship core:linkedInformationResource ?publication .
     ?publication core:informationResourceInAuthorship ?coAuthorship .
     ?coAuthorship ?property1 ?object1 .
     ?coAuthorship core:linkedAuthor ?person .
     ?person ?property2 ?object2 .
}