PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?person ?property ?object .   
} WHERE {
     PERSON_URI core:authorInAuthorship ?authorship . 
     ?authorship core:linkedAuthor ?person .
     ?person ?property ?object .   
}