PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>PREFIX bibo: <http://purl.org/ontology/bibo/>

CONSTRUCT {
     ?endDate ?property ?object .
     ?precision ?property2 ?object2 .
} WHERE {
     PERSON_URI core:relatedBy ?authorship . 
     ?authorship a core:Authorship .
     ?authorship core:relates ?publication .
     ?publication a obo:IAO_0000030 .
     ?publication bibo:presentedAt ?event .
     ?event ?property ?object .
     ?event core:dateTimeInterval ?dateTimeInterval .
     ?dateTimeInterval core:end ?endDate .
     ?endDate core:dateTimePrecision ?precision .
     ?precision ?property2 ?object2 .
}