PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?publisher ?property ?object .   
} WHERE {
     PERSON_URI core:authorInAuthorship ?authorship . 
     ?authorship core:linkedInformationResource ?publication .
     ?publication core:hasPublicationVenue ?publicationVenue .
     ?publicationVenue core:publisher ?publisher . 
     ?publisher ?property ?object .  
}