PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
     ?publisher rdfs:label ?label .   
} WHERE {
     PERSON_URI core:authorInAuthorship ?authorship . 
     ?authorship core:linkedInformationResource ?publication .
     ?publication core:publisher ?publisher . 
     ?publisher rdfs:label ?label .  
}