PREFIX core: <http://vivoweb.org/ontology/core#>

CONSTRUCT {
     ?informationResource ?property ?object .
} WHERE {
     PERSON_URI core:authorInAuthorship ?authorship . 
     ?authorship core:linkedInformationResource ?publication .
     ?publication core:partOf ?informationResource .
     ?informationResource ?property ?object .
}