name: Docker

on:
  push:
    branches:
      - VIVO-1961
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: -Xmx1024M

    steps:
      - uses: actions/checkout@v2

      - name: Clone Vitro
        run: git clone https://github.com/vivo-project/Vitro.git ../Vitro

      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cache-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-cache-m2-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Build
        run: mvn clean install

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vivoweb/vivo
          tag_with_ref: true

