PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
     ?grant ?property ?object .
     ?investigatorRole core:roleContributesTo ?grant .
} WHERE {
    {
      {PERSON_URI core:hasPrincipalInvestigatorRole ?investigatorRole }
        union
      {PERSON_URI core:hasCo-PrincipalInvestigatorRole ?investigatorRole }   
     }
     
     ?investigatorRole core:roleContributesTo ?grant .
     ?grant a core:Grant .
     ?grant ?property ?object 
}