PREFIX core: <http://vivoweb.org/ontology/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
     ?investigatorRole core:roleContributesTo ?grant .
     ?grant core:grantAwardedBy ?awardingOrganization .
     ?awardingOrganization rdfs:label ?label 
} WHERE {
    {
      {PERSON_URI core:hasPrincipalInvestigatorRole ?investigatorRole }
        union
      {PERSON_URI core:hasCo-PrincipalInvestigatorRole ?investigatorRole }   
     }
     
     ?investigatorRole core:roleContributesTo ?grant .
     ?grant a core:Grant .
     ?grant core:grantAwardedBy ?awardingOrganization .
     ?awardingOrganization rdfs:label ?label 
}